sudo: required
dist: trusty
language: cpp

services:
  - docker

before_install:
  - docker build -t build_ref -f tools/docker_image .

script:
  - docker run build_ref /bin/bash -c "tools/clang_format_check.sh"
  - docker run build_ref /bin/bash -c "make debug"
  - docker run build_ref /bin/bash -c "make release"
